function [Timestamp,torso_joints] = importfile_joints_torso(filename, startRow, endRow)
%IMPORTFILE_JOINTS_TORSO Import numeric data from a text file as column vectors.
%   [TIMESTAMP,TORSO_JOINTS] = IMPORTFILE_JOINTS_TORSO(FILENAME) Reads
%   data from text file FILENAME for the default selection.
%
%   [TIMESTAMP,TORSO_JOINTS] = IMPORTFILE_JOINTS_TORSO(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   [Timestamp,torso_joints] = importfile_joints_torso('data.log',1, 4984);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/09/14 17:14:55

%% Initialize variables.
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%5f%18f%18f%10f%9f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Timestamp = dataArray{:, 3};
j0 = dataArray{:, 4};
j1 = dataArray{:, 5};
j2 = dataArray{:, 6};
torso_joints = [j0 j1 j2];


